encoding: UTF-8
name: jamesdonanaldson.io
markdown: redcarpet
highlighter: pygments
description: "Blog for James Donaldson - web developer and Phd research based in Belfast, Northern Ireland."
url: "http://jamesdonaldson.io"
baseurl: http://jamesdonaldson.io
permalink: pretty